// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge.proto

package pb // import "./pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 接口请求入参
type JudgeRequest struct {
	SourceCode           []byte   `protobuf:"bytes,1,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProblemID            int32    `protobuf:"varint,3,opt,name=problemID,proto3" json:"problemID,omitempty"`
	UserID               int32    `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	IsUpdate             bool     `protobuf:"varint,5,opt,name=isUpdate,proto3" json:"isUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_judge_0234f45bb9868b82, []int{0}
}
func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (dst *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(dst, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetSourceCode() []byte {
	if m != nil {
		return m.SourceCode
	}
	return nil
}

func (m *JudgeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JudgeRequest) GetProblemID() int32 {
	if m != nil {
		return m.ProblemID
	}
	return 0
}

func (m *JudgeRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *JudgeRequest) GetIsUpdate() bool {
	if m != nil {
		return m.IsUpdate
	}
	return false
}

// 接口返回出参
type JudgeResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_judge_0234f45bb9868b82, []int{1}
}
func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (dst *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(dst, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

func (m *JudgeResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*JudgeRequest)(nil), "pb.JudgeRequest")
	proto.RegisterType((*JudgeResponse)(nil), "pb.JudgeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JudgeServiceClient is the client API for JudgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JudgeServiceClient interface {
	// 一个简单的rpc
	Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error)
}

type judgeServiceClient struct {
	cc *grpc.ClientConn
}

func NewJudgeServiceClient(cc *grpc.ClientConn) JudgeServiceClient {
	return &judgeServiceClient{cc}
}

func (c *judgeServiceClient) Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error) {
	out := new(JudgeResponse)
	err := c.cc.Invoke(ctx, "/pb.JudgeService/Judge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServiceServer is the server API for JudgeService service.
type JudgeServiceServer interface {
	// 一个简单的rpc
	Judge(context.Context, *JudgeRequest) (*JudgeResponse, error)
}

func RegisterJudgeServiceServer(s *grpc.Server, srv JudgeServiceServer) {
	s.RegisterService(&_JudgeService_serviceDesc, srv)
}

func _JudgeService_Judge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).Judge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JudgeService/Judge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).Judge(ctx, req.(*JudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JudgeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.JudgeService",
	HandlerType: (*JudgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Judge",
			Handler:    _JudgeService_Judge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge.proto",
}

func init() { proto.RegisterFile("judge.proto", fileDescriptor_judge_0234f45bb9868b82) }

var fileDescriptor_judge_0234f45bb9868b82 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x4d, 0x9d, 0x19, 0x3a, 0xd7, 0x0a, 0x7a, 0x17, 0x12, 0x8a, 0xc8, 0x30, 0xab, 0x80,
	0x10, 0x41, 0xf7, 0x2e, 0xb4, 0x9b, 0xba, 0x8c, 0xb8, 0x71, 0x67, 0x3a, 0x17, 0xa9, 0xa8, 0xb9,
	0xe6, 0x47, 0xf0, 0x3d, 0x7c, 0x60, 0x69, 0x0c, 0xd3, 0xd9, 0x9d, 0xef, 0x4b, 0x02, 0xe7, 0x04,
	0x8e, 0xde, 0xd2, 0xf0, 0x4a, 0x9a, 0xbd, 0x8b, 0x0e, 0x67, 0x6c, 0xfb, 0x5f, 0x01, 0x8b, 0x87,
	0x9d, 0x33, 0xf4, 0x95, 0x28, 0x44, 0xbc, 0x00, 0x08, 0x2e, 0xf9, 0x0d, 0xdd, 0xbb, 0x81, 0xa4,
	0xe8, 0x84, 0x5a, 0x98, 0x89, 0x41, 0x84, 0x2a, 0xfe, 0x30, 0xc9, 0x59, 0x27, 0x54, 0x6b, 0x72,
	0xc6, 0x73, 0x68, 0xd9, 0x3b, 0xfb, 0x4e, 0x1f, 0xeb, 0x95, 0x3c, 0xec, 0x84, 0xaa, 0xcd, 0x5e,
	0xe0, 0x19, 0x34, 0x29, 0x90, 0x5f, 0xaf, 0x64, 0x95, 0x8f, 0x0a, 0xe1, 0x12, 0xe6, 0xdb, 0xf0,
	0xc4, 0xc3, 0x4b, 0x24, 0x59, 0x77, 0x42, 0xcd, 0xcd, 0xc8, 0xfd, 0x25, 0x1c, 0x97, 0x56, 0x81,
	0xdd, 0x67, 0xa0, 0xdd, 0x65, 0x5f, 0x72, 0x2e, 0xd5, 0x9a, 0x91, 0xaf, 0x6f, 0xcb, 0x84, 0x47,
	0xf2, 0xdf, 0xdb, 0x0d, 0xa1, 0x86, 0x3a, 0x33, 0x9e, 0x68, 0xb6, 0x7a, 0xba, 0x6e, 0x79, 0x3a,
	0x31, 0xff, 0xaf, 0xfb, 0x83, 0xbb, 0xe6, 0xb9, 0xd2, 0x57, 0x6c, 0x6d, 0x93, 0xbf, 0xe5, 0xe6,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x89, 0x45, 0x30, 0xdc, 0x25, 0x01, 0x00, 0x00,
}
